/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bSV8jZmwKUXbKUfHtNz4tk

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsd5Rkp1Qvoord } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: d5rkp1qvoord/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsd5Rkp1Qvoord
});
